### ISSUE TITLE
LRP analysis of an AMORE model translated to neuralnet using the tansig activation function

### ISSUE THREAD

**Issue by JoseDiogoMarquesdosSantos** [bips-hb/innsight#11]
I have a neural network model to classify motor fMRI data that was initially developed in AMORE and thus uses the "tansig" activation function ( tansig(x) = 1.7159*tanh(x*2/3) ). However, as AMORE isn't a supported package I copied the model over to neuralnet, but their activation function is simply tanh(x). This leads to different classifications in a small number of cases. The problem in neuralnet is solved easily by implementing the tansig function as a custom activation function, but innsight doesn't allow for custom activations functions. As the difference between the functions is simply the multiplication by 2 constants, what would be a possible workaround for this?

**Comment by nkoenen** [comment]
Hi Jose,

Unfortunately, this is not possible without further work, but I have created a workaround on the branch 'New_Features' , which will also be part of the package soon. In this version, the package takes the custom activation and tests if it is `torch`-compatible. 

See the following example:

```r
# Install the package from the branch 'New_Features'
devtools::install_github("bips-hb/innsight", ref = "New_Features")

# Train a neural network (just to make a working example)
library(innsight)
library(neuralnet)
data(iris)

# Train a neural network
nn <- neuralnet((Species == "setosa") ~ Petal.Length + Petal.Width,  iris,
                linear.output = FALSE, hidden = c(3, 2), rep = 1,
                act.fct = function(x) 1.7159 * tanh(2*x/ 3)
)

# Convert the model
converter <- Converter$new(nn)

# Apply, e.g., LRP
lrp <- LRP$new(converter, matrix(rnorm(20), 10,2))
```

I hope this helps you. Otherwise, I will gladly help you again.

Best,
Niklas
